// Auto-generated from accounting_game_db (2).csv
const accountingGameData = [
  {
    "Product": "Money-market loan - Amortized Cost asset",
    "Financial_event": "Asset recognition",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "Loan",
    "Credit_account_label": "Loan Payable",
    "Reversed": "No",
    "Description": "According to IFRS 9, Loans remain classified as financial assets but \"Loans and receivables\" category do no longer exist as such. Indeed in IFRS 9, Amortized Cost measurement of financial assets, hence loans, remains possible given the objective is to hold assets to collect contractual cash flows, which is the case for money marfket loans. Otherwise, Loans are measured at Fair Value Through Profit or Loss (FVTPL).",
    "Help": "Trade date operation"
  },
  {
    "Product": "Money-market loan - Amortized Cost asset",
    "Financial_event": "Cash settlement",
    "Financial_event_step": "2",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "Loan Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Start date operation"
  },
  {
    "Product": "Money-market loan - Amortized Cost asset",
    "Financial_event": "Value measurement",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest accruals",
    "Debit_account_label": "Interest receivable",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrual of the interests"
  },
  {
    "Product": "Money-market loan - Amortized Cost asset",
    "Financial_event": "Realized income",
    "Financial_event_step": "4",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Realized interests"
  },
  {
    "Product": "Money-market loan - Amortized Cost asset",
    "Financial_event": "Asset derecognition",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Redeemed capital",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Loan",
    "Reversed": "No",
    "Description": "",
    "Help": "Maturity date operation, return capital"
  },
  {
    "Product": "Money-market deposit - Amortized Cost liability",
    "Financial_event": "Liability recognition",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "Deposit Receivable",
    "Credit_account_label": "Deposit",
    "Reversed": "No",
    "Description": "Deposits are loans seen on the borrower side, i.e. over-the-counter contracts where one party (borrower) agrees to \nborrow capital to another party (lender) for a determined period of time against a fix or floating interest payment.",
    "Help": "Trade date operation"
  },
  {
    "Product": "Money-market deposit - Amortized Cost liability",
    "Financial_event": "Cash settlement",
    "Financial_event_step": "2",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Deposit Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Start date operation"
  },
  {
    "Product": "Money-market deposit - Amortized Cost liability",
    "Financial_event": "Value measurement",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest accruals",
    "Debit_account_label": "Interest Expense",
    "Credit_account_label": "Interest Payable",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrual of the interests"
  },
  {
    "Product": "Money-market deposit - Amortized Cost liability",
    "Financial_event": "Realized loss",
    "Financial_event_step": "4",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest",
    "Debit_account_label": "Interest Expense",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Realized interests"
  },
  {
    "Product": "Money-market deposit - Amortized Cost liability",
    "Financial_event": "Liability derecognition",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Redeemed capital",
    "Debit_account_label": "Deposit",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Maturity date operation, return capital"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "OBS commitment (leg 1) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "FX Spot and FX Forward are over-the-counter contracts between two parties in order to exchange a certain amount of currencies at a specified time, at a rate agreed at the time of the transaction. The difference between FX spot and FX forward contracts is the settlement delay which is usually 0 to 2 business days for spot contracts, and more than two business days for forward contracts.",
    "Help": "Commit notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "OBS commitment (leg 2) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty commits notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "Value measurement",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Revaluation (MTM) - Profit",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation at profit"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "OBS uncommitment (leg 1) - Payable",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Uncommit notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "OBS uncommitment (leg 2) - Receivable",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty uncommits notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Profit",
    "Financial_event": "Realized income or expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Cash settlement",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": "FX settlement at profit"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "OBS commitment (leg 1) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "FX Spot and FX Forward are over-the-counter contracts between two parties in order to exchange a certain amount of currencies at a specified time, at a rate agreed at the time of the transaction. The difference between FX spot and FX forward contracts is the settlement delay which is usually 0 to 2 business days for spot contracts, and more than two business days for forward contracts.",
    "Help": "Commit notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "OBS commitment (leg 2) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty commits notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "Value measurement",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Revaluation (MTM) - Loss",
    "Debit_account_label": "MTM Loss",
    "Credit_account_label": "Unrealized liability",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation at Loss"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "OBS uncommitment (leg 1) - Payable",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Uncommit notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "OBS uncommitment (leg 2) - Receivable",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty uncommits notional (OBS)"
  },
  {
    "Product": "FX Spot and FX Forward - Trading - Loss",
    "Financial_event": "Realized income or expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Cash settlement",
    "Debit_account_label": "Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "FX settlement at loss"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS commitment (Near leg - Buy currency) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "A FX Swap is an over-the-counter contract between two parties made of 2 legs that can be considered 2 successive spot/forward transactions. A Near Leg: the two parties agree to exchange one currency against another at an initial date (First Value Date) for a first exchange rate. A Far Leg: the two parties agree to exchange back the same currencies at a future date compared to initial date (Second Value Date) for a second exchange rate. The difference between the exchange rate applied on near and far leg reflects the interest differentials between the two  currencies concerned, also called swap points.",
    "Help": "Trade date"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS commitment (Near leg - Sell currency) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS commitment (Far leg - Buy currency) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS commitment (Far leg - Sell currency) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "Value measurement (Near leg) - Profit",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Revaluation (MTM) - Profit",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation - Gain"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "Value measurement (Far leg) - Profit",
    "Financial_event_step": "2",
    "Financial_event_amount": "2",
    "Financial_event_type": "Revaluation (MTM) - Profit",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "Realized result (Near leg)",
    "Financial_event_step": "3",
    "Financial_event_amount": "1",
    "Financial_event_type": "Realized Gain",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": "Realized Gain"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "Value measurement (Far leg) - Profit",
    "Financial_event_step": "4",
    "Financial_event_amount": "1",
    "Financial_event_type": "Revaluation (MTM) - Loss",
    "Debit_account_label": "MTM Loss",
    "Credit_account_label": "Unrealized Liability",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation - Loss"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "Realized result (Far leg)",
    "Financial_event_step": "5",
    "Financial_event_amount": "1",
    "Financial_event_type": "Realized Loss",
    "Debit_account_label": "Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Realized Loss"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS uncommitment (Near leg - Buy currency) - Receivable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Expiry date"
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS uncommitment (Near leg - Sell currency) - Payable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS uncommitment (Far leg - Buy currency) - Receivable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Swap - Trading derivative",
    "Financial_event": "OBS uncommitment (Far leg - Sell currency) - Payable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "OBS commitment (Buy currency) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Cont Buy Call Recbl",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "A FX option is an over-the-counter contract involving two parties, the buyer and the seller of the option, that agree on the following conditions: A right for the buyer, not an obligation, to exchange a certain amount of one currency against another currency at a pre-agreed exchange rate on a specified date. The type of the option, a call or a put option, respectively the right to buy or sell a currency against the other.",
    "Help": "Trade date"
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "OBS commitment (Sell currency) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Cont Buy Call Paybl",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "Expense deferral",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Premium",
    "Debit_account_label": "Deferred Loss",
    "Credit_account_label": "Premium Payable",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "Cash settlement",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Premium",
    "Debit_account_label": "Premium Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "Settlement",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "Value measurement - Gain",
    "Financial_event_step": "3",
    "Financial_event_amount": "11",
    "Financial_event_type": "Revaluation (MTM)",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "Revaluation",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "Realized deferred expense",
    "Financial_event_step": "4",
    "Financial_event_amount": "10",
    "Financial_event_type": "Premium",
    "Debit_account_label": "Premium Expense",
    "Credit_account_label": "Deferred Loss",
    "Reversed": "No",
    "Description": "Deal termination",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "OBS uncommitment (Buy currency) - Receivable",
    "Financial_event_step": "4",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Cont Buy Call Recbl",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "FX Option - Trading derivative - Buy call",
    "Financial_event": "OBS uncommitment (Sell currency) - Payable",
    "Financial_event_step": "4",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Cont Buy Call Paybl",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "OBS commitment (leg 1) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "An interest rate swap (IRS) is an arrangement between two parties to exchange interest rate denominated in the same currency at predetermined conditions, for a certain amount of notional and over a certain period of time. If the IRS is not traded at fair value, a premium will be exchanged at inception between the two parties to compensate the gain or loss towards fair value.",
    "Help": "Commit notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "OBS commitment (leg 2) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty commits notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "Unrealized premium",
    "Financial_event_step": "2",
    "Financial_event_amount": "100",
    "Financial_event_type": "Premium Payable",
    "Debit_account_label": "Premium Expense",
    "Credit_account_label": "Premium Payable",
    "Reversed": "No",
    "Description": "",
    "Help": "Unrealized payable premium"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "Cash settlement",
    "Financial_event_step": "3",
    "Financial_event_amount": "100",
    "Financial_event_type": "Premium Pay",
    "Debit_account_label": "Premium Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Premium payment"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "Value measurement",
    "Financial_event_step": "4",
    "Financial_event_amount": "10",
    "Financial_event_type": "Revaluation (MTM) - Loss",
    "Debit_account_label": "MTM Loss",
    "Credit_account_label": "Unrealized liability",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation at Loss"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "Realized income or expense",
    "Financial_event_step": "5",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest Pay",
    "Debit_account_label": "Interest Expense",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Interest payment"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "OBS uncommitment (leg 1) - Payable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Uncommit notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Loss",
    "Financial_event": "OBS uncommitment (leg 2) - Receivable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty uncommits notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "OBS commitment (leg 1) - Payable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "An interest rate swap (IRS) is an arrangement between two parties to exchange interest rate denominated in the same currency at predetermined conditions, for a certain amount of notional and over a certain period of time. If the IRS is not traded at fair value, a premium will be exchanged at inception between the two parties to compensate the gain or loss towards fair value.",
    "Help": "Commit notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "OBS commitment (leg 2) - Receivable",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty commits notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "Unrealized premium",
    "Financial_event_step": "2",
    "Financial_event_amount": "100",
    "Financial_event_type": "Premium Receivable",
    "Debit_account_label": "Premium Receivable",
    "Credit_account_label": "Premium Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Unrealized receivable premium"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "Premium cash settlement",
    "Financial_event_step": "3",
    "Financial_event_amount": "100",
    "Financial_event_type": "Premium Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Premium Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Premium payment"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "Value measurement",
    "Financial_event_step": "4",
    "Financial_event_amount": "10",
    "Financial_event_type": "Revaluation (MTM) - Profit",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation at Profit"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "Realized income or expense",
    "Financial_event_step": "5",
    "Financial_event_amount": "10",
    "Financial_event_type": "Interest Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Interest receive"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "OBS uncommitment (leg 1) - Payable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional payable",
    "Debit_account_label": "Contingent Payable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": "Uncommit notional (OBS)"
  },
  {
    "Product": "Interest rate swap - Trading derivative - Profit",
    "Financial_event": "OBS uncommitment (leg 2) - Receivable",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional receivable",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Counterparty uncommits notional (OBS)"
  },
  {
    "Product": "Equity - FVTPL - Purchased and held",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "According to IFRS 9, Equitiy assets do not give birth to contractual cash flows which are payments of principal and interests, and must then be measured at Fair Value Through Profit or Loss (FVTPL).",
    "Help": "Trade date"
  },
  {
    "Product": "Equity - FVTPL - Purchased and held",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Settle equity with cash"
  },
  {
    "Product": "Equity - FVTPL - Purchased and held",
    "Financial_event": "Revaluation (MTM) - Profit",
    "Financial_event_step": "3",
    "Financial_event_amount": "156",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Reval at MTM"
  },
  {
    "Product": "Equity - FVTPL - Purchased and held",
    "Financial_event": "CA Commitment Cash Dividend",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "Inventory Position (Corporate action)",
    "Debit_account_label": "Dividend Receivable",
    "Credit_account_label": "Dividend Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Dividend commitment"
  },
  {
    "Product": "Equity - FVTPL - Purchased and held",
    "Financial_event": "CA Cash Dividend",
    "Financial_event_step": "5",
    "Financial_event_amount": "2",
    "Financial_event_type": "Inventory Position (Corporate action)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Dividend Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Dividend payment"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "According to IFRS 9, Equitiy assets do not give birth to contractual cash flows which are payments of principal and interests, and must then be measured at Fair Value Through Profit or Loss (FVTPL).",
    "Help": "Trade"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Settle equity"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Revaluation (MTM) - Profit",
    "Financial_event_step": "3",
    "Financial_event_amount": "156",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Reval at MTM"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Realized Gain @ClosingDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "3",
    "Financial_event_type": "PnL",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale of equity)"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Nominal Receivable@TradeDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "156",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Receivable",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a profit",
    "Financial_event": "Nominal Receive@PaymentDate",
    "Financial_event_step": "5",
    "Financial_event_amount": "156",
    "Financial_event_type": "Nominal Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Equity Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Payment of equity by counterparty"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "According to IFRS 9, Equitiy assets do not give birth to contractual cash flows which are payments of principal and interests, and must then be measured at Fair Value Through Profit or Loss (FVTPL).",
    "Help": "Trade"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Settle equity"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Revaluation (MTM) - Profit",
    "Financial_event_step": "3",
    "Financial_event_amount": "149",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "MTM Loss",
    "Credit_account_label": "Unrealized Liability",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Reval at MTM"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Realized Loss @ClosingDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "4",
    "Financial_event_type": "PnL",
    "Debit_account_label": "Realized Loss",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale of equity)"
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Nominal Receivable@TradeDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "149",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Receivable",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTPL - Purchased and sold for a loss",
    "Financial_event": "Nominal Receive@PaymentDate",
    "Financial_event_step": "5",
    "Financial_event_amount": "149",
    "Financial_event_type": "Nominal Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Equity Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Payment of equity by counterparty"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and held",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "You would account for an equity instrument at FVTOCI to reflect long?term, non?trading investments in a way that avoids profit?or?loss volatility while still measuring them at fair value.",
    "Help": ""
  },
  {
    "Product": "Equity - FVTOCI - Purchased and held",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTOCI - Purchased and held",
    "Financial_event": "Revaluation (MTM) - Profit",
    "Financial_event_step": "3",
    "Financial_event_amount": "156",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "Equity OCI",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTOCI - Purchased and held",
    "Financial_event": "CA Commitment Cash Dividend",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "Inventory Position (Corporate action)",
    "Debit_account_label": "Dividend Receivable",
    "Credit_account_label": "Dividend Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Dividend commitment"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and held",
    "Financial_event": "CA Cash Dividend",
    "Financial_event_step": "5",
    "Financial_event_amount": "2",
    "Financial_event_type": "Inventory Position (Corporate action)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Dividend Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Dividend payment"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "You would account for an equity instrument at FVTOCI to reflect long?term, non?trading investments in a way that avoids profit?or?loss volatility while still measuring them at fair value.",
    "Help": "Trade"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Settle equity"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Revaluation (MTM) - Profit",
    "Financial_event_step": "3",
    "Financial_event_amount": "156",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "Equity OCI",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Reval at MTM"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Realized Profit @ClosingDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "3",
    "Financial_event_type": "PnL",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale of equity)"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Nominal Receivable@TradeDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "156",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Receivable",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a profit",
    "Financial_event": "Nominal Receive@PaymentDate",
    "Financial_event_step": "5",
    "Financial_event_amount": "156",
    "Financial_event_type": "Nominal Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Equity Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Payment of equity by counterparty"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Nominal Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Nominal",
    "Credit_account_label": "Equity Payable",
    "Reversed": "No",
    "Description": "You would account for an equity instrument at FVTOCI to reflect long?term, non?trading investments in a way that avoids profit?or?loss volatility while still measuring them at fair value.",
    "Help": "Trade"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Nominal Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "153",
    "Financial_event_type": "Nominal Pay",
    "Debit_account_label": "Equity Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Settle equity"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Revaluation (MTM) - Loss",
    "Financial_event_step": "3",
    "Financial_event_amount": "149",
    "Financial_event_type": "Inventory Position",
    "Debit_account_label": "Equity OCI",
    "Credit_account_label": "Unrealized Liability",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Reval at MTM"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Realized Loss @ClosingDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "4",
    "Financial_event_type": "PnL",
    "Debit_account_label": "Realized Loss",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale of equity)"
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Nominal Receivable@TradeDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "149",
    "Financial_event_type": "Nominal Trade",
    "Debit_account_label": "Equity Receivable",
    "Credit_account_label": "Equity Nominal",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Equity - FVTOCI - Purchased and sold for a loss",
    "Financial_event": "Nominal Receive@PaymentDate",
    "Financial_event_step": "5",
    "Financial_event_amount": "149",
    "Financial_event_type": "Nominal Receive",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Equity Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Payment of equity by counterparty"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond measured at amortized cost is recorded based on its initial value adjusted over time for principal repayments and interest using the effective interest method, with no fair value changes recognized in profit or loss.",
    "Help": "Trade date"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade commitment - Premium",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "2",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade uncommitment - Premium",
    "Financial_event_step": "2",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "3",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Write purchase to BS"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Bonds premium amortization",
    "Financial_event_step": "4",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": "Amortize premium through expense"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Coupon received",
    "Financial_event_step": "5",
    "Financial_event_amount": "20",
    "Financial_event_type": "Interest",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Coupon"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Redemption",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Principal",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": "Maturity"
  },
  {
    "Product": "Bond - Amortized Cost - Held to maturity",
    "Financial_event": "Redemption - Realized P/L Loss",
    "Financial_event_step": "6",
    "Financial_event_amount": "50",
    "Financial_event_type": "P&L",
    "Debit_account_label": "POS Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Capital purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond at amortized cost is a debt investment measured at its initial value adjusted over time for principal repayments and the amortization of any discount or premium, rather than being revalued at current market prices.",
    "Help": "Trade date (purchase)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Premium purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Accruals purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Capital purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date (purchase)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Premium purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Accruals purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "2",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "3",
    "Financial_event_amount": "2",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Capital sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Premium sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "60",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Accruals sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Capital sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date (sale)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Premium sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "60",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Accruals sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "AC Bonds Cash delivery - Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Cost FIFO or AVP (clean)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Bonds Accrued Interest - Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Bonds Realized PL @ value date\nProfit on Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "30",
    "Financial_event_type": "Realized PL",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "POS Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Premium and sold for profit",
    "Financial_event": "Realized Amortization @ value date\nProfit on Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "4",
    "Financial_event_type": "Realized Amortization",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "POS Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Capital purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond at amortized cost is a debt investment measured at its initial value adjusted over time for principal repayments and the amortization of any discount or premium, rather than being revalued at current market prices.",
    "Help": "Trade date (purchase)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Discount purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Accruals purchase",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Capital purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date (purchase)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Discount purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Accruals purchase",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "2",
    "Financial_event_amount": "950",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "2",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "3",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Capital sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Trade date (sale)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Premium sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "60",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Accruals sale",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Capital sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date (sale)"
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Premium sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Accruals sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "AC Bonds Cash delivery - Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "950",
    "Financial_event_type": "Cost FIFO or AVP (clean)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Bonds Accrued Interest - Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Bonds Realized PL @ value date Loss on Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "20",
    "Financial_event_type": "Realized PL",
    "Debit_account_label": "POS Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - Amortized Cost - Purchased  @Discount and sold for loss",
    "Financial_event": "Realized Amortization @ value date Loss on Sale",
    "Financial_event_step": "5",
    "Financial_event_amount": "4",
    "Financial_event_type": "Realized Amortization",
    "Debit_account_label": "POS Realized Loss",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond measured at FVTPL is revalued at fair value each period, with all gains or losses immediately recognized in profit or loss.",
    "Help": "Trade date"
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade commitment - Premium",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "FV OBS Valuation (profit)",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Unreal. UnSettl. POS",
    "Credit_account_label": "UnSettl.POS MtM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date"
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Premium",
    "Financial_event_step": "3",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "3",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests and MTM valuation"
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "FV BS Valuation (profit)",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Coupon received",
    "Financial_event_step": "5",
    "Financial_event_amount": "20",
    "Financial_event_type": "Interest",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Coupon payment"
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Redemption (Cost)",
    "Financial_event_step": "6",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Principal",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": "Redemption at purchase price"
  },
  {
    "Product": "Bond - FVTPL - Held  to maturity",
    "Financial_event": "Redemption - Realized P/L Loss",
    "Financial_event_step": "6",
    "Financial_event_amount": "50",
    "Financial_event_type": "P&L",
    "Debit_account_label": "POS Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond measured at FVTOCI is carried at fair value, but unrealized gains or losses go to other comprehensive income while interest revenue and impairments affect profit or loss.",
    "Help": "Trade date"
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade commitment - Premium",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "FV OBS Valuation (profit)",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Unreal. UnSettl. POS",
    "Credit_account_label": "UnSettl.POS MtM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date"
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Premium",
    "Financial_event_step": "3",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "3",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests and MTM valuation"
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "FVTOCI Position Valuation (profit)",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Equity OCI",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Bond Premium Amortization",
    "Financial_event_step": "5",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Coupon received",
    "Financial_event_step": "6",
    "Financial_event_amount": "20",
    "Financial_event_type": "Interest",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": "Coupon payment"
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Redemption (Cost)",
    "Financial_event_step": "7",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Principal",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": "Redemption at purchase price"
  },
  {
    "Product": "Bond - FVTOCI - Held  to maturity",
    "Financial_event": "Redemption - Realized P/L Loss",
    "Financial_event_step": "7",
    "Financial_event_amount": "50",
    "Financial_event_type": "P&L",
    "Debit_account_label": "POS Realized Loss",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond measured at FVTOCI is carried at fair value, but unrealized gains or losses go to other comprehensive income while interest revenue and impairments affect profit or loss.",
    "Help": "Trade date"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Premium",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "FV OBS Valuation (profit)",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Unreal. UnSettl. POS",
    "Credit_account_label": "UnSettl.POS MtM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "OBS revaluation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Premium",
    "Financial_event_step": "3",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "3",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests and MTM valuation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "MTM FVTOCI POS BS Value measurement - Profit",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "MTM",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Equity OCI",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Sell the bond for profit"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Premium",
    "Financial_event_step": "5",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "5",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "FV OBS Valuation (Profit)",
    "Financial_event_step": "6",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Unreal. UnSettl. POS",
    "Credit_account_label": "UnSettl.POS MtM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "OBS revaluation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "7",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": "Sale settlement"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Premium",
    "Financial_event_step": "7",
    "Financial_event_amount": "50",
    "Financial_event_type": "Premium",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "7",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Bond cash delivery sale trade",
    "Financial_event_step": "7",
    "Financial_event_amount": "1050",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Accrued interests sale",
    "Financial_event_step": "7",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Realized PL Profit on sale @value date",
    "Financial_event_step": "7",
    "Financial_event_amount": "30",
    "Financial_event_type": "PnL",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Premium and sold for profit",
    "Financial_event": "Realized amortization @value date profit on sale",
    "Financial_event_step": "7",
    "Financial_event_amount": "4",
    "Financial_event_type": "Amortization",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "A bond measured at FVTOCI is carried at fair value, but unrealized gains or losses go to other comprehensive income while interest revenue and impairments affect profit or loss.",
    "Help": "Trade date"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Discount",
    "Financial_event_step": "1",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "1",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "FV OBS Valuation (profit)",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value profit",
    "Debit_account_label": "Unreal. UnSettl. POS",
    "Credit_account_label": "UnSettl.POS MtM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "OBS revaluation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "3",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement date"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Discount",
    "Financial_event_step": "3",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Asset position opening",
    "Financial_event_step": "3",
    "Financial_event_amount": "950",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Carrying Amount",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Realized interest expense",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accrued interest purchased",
    "Debit_account_label": "Interest Income",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Accrued interest",
    "Financial_event_step": "4",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Accrued Interests",
    "Credit_account_label": "Interest Income",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Accrued interests and MTM valuation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "MTM FVTOCI POS BS Value measurement - Loss",
    "Financial_event_step": "4",
    "Financial_event_amount": "2",
    "Financial_event_type": "MTM",
    "Debit_account_label": "Equity OCI",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "Yes",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Capital",
    "Financial_event_step": "5",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": "Sell the bond for profit"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Discount",
    "Financial_event_step": "5",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade commitment - Accruals",
    "Financial_event_step": "5",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Offset",
    "Credit_account_label": "OBS Trade Commitment",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "FV OBS Valuation (Loss)",
    "Financial_event_step": "6",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fair value loss",
    "Debit_account_label": "UnSettl.POS MtM Loss",
    "Credit_account_label": "Unreal. UnSettl. POS",
    "Reversed": "Yes",
    "Description": "",
    "Help": "OBS revaluation"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Capital",
    "Financial_event_step": "7",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Initial capital",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": "Sale settlement"
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Discount",
    "Financial_event_step": "7",
    "Financial_event_amount": "50",
    "Financial_event_type": "Discount",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "OBS trade uncommitment - Accruals",
    "Financial_event_step": "7",
    "Financial_event_amount": "10",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "OBS Trade Commitment",
    "Credit_account_label": "OBS Offset",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Bond cash delivery sale trade",
    "Financial_event_step": "7",
    "Financial_event_amount": "950",
    "Financial_event_type": "Purchase price (Clean)",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Carrying Amount",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Accrued interests sale",
    "Financial_event_step": "7",
    "Financial_event_amount": "12",
    "Financial_event_type": "Accruals",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Realized PL Loss on sale @value date",
    "Financial_event_step": "7",
    "Financial_event_amount": "30",
    "Financial_event_type": "PnL",
    "Debit_account_label": "POS Realized Gain",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Bond - FVTOCI - Purchased @Discount and sold for loss",
    "Financial_event": "Realized amortization @value date loss on sale",
    "Financial_event_step": "7",
    "Financial_event_amount": "4",
    "Financial_event_type": "Amortization",
    "Debit_account_label": "POS Realized Gain",
    "Credit_account_label": "Interest Income",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "OBS Notional Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "A commodity cleared swap is a standardized, plain vanilla OTC commodity swap, centrally cleared on the Exchange.",
    "Help": "Trade date"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "OBS Notional Receivable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "Brokerage Payable@TradeDate",
    "Financial_event_step": "1",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fees",
    "Debit_account_label": "Brokerage Expense",
    "Credit_account_label": "Brokerage Payable",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "Brokerage Pay@PaymentDate",
    "Financial_event_step": "2",
    "Financial_event_amount": "1",
    "Financial_event_type": "Fees",
    "Debit_account_label": "Brokerage Payable",
    "Credit_account_label": "Cash Nostro",
    "Reversed": "No",
    "Description": "",
    "Help": "Payment date"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "Revaluation (MtM) - Gain",
    "Financial_event_step": "3",
    "Financial_event_amount": "10",
    "Financial_event_type": "Revaluation amount",
    "Debit_account_label": "Unrealized Asset",
    "Credit_account_label": "MTM Gain",
    "Reversed": "Yes",
    "Description": "",
    "Help": "Revaluation"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "Cash Settlement Receivable@TradeDate",
    "Financial_event_step": "4",
    "Financial_event_amount": "5",
    "Financial_event_type": "Settlement amount",
    "Debit_account_label": "Settlement Receivable",
    "Credit_account_label": "Realized Gain",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement trade date"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "Cash Settlement Receive@PaymentDate",
    "Financial_event_step": "5",
    "Financial_event_amount": "5",
    "Financial_event_type": "Settlement amount",
    "Debit_account_label": "Cash Nostro",
    "Credit_account_label": "Settlement Receivable",
    "Reversed": "No",
    "Description": "",
    "Help": "Settlement payment date"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "OBS Notional Payable reversal@Maturity",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Contra",
    "Credit_account_label": "Contingent Payable",
    "Reversed": "No",
    "Description": "",
    "Help": "Expiry date"
  },
  {
    "Product": "Commodities Cleared Swap - Trading derivative - Profit",
    "Financial_event": "OBS Notional Receivable reversal@Maturity",
    "Financial_event_step": "6",
    "Financial_event_amount": "1000",
    "Financial_event_type": "Notional",
    "Debit_account_label": "Contingent Receivable",
    "Credit_account_label": "Contingent Contra",
    "Reversed": "No",
    "Description": "",
    "Help": ""
  }
];
